version: '25.0.3'  
services:
  web:
    build: . 
    ports:
      - "3000:3000"  
    depends_on:
      - db  

  db:
    image: postgres:13
    env_file:
      - .env 
    ports:
      - "5432:5432"  
    volumes:
      - db-data:/var/lib/postgresql/data 

volumes:
  db-data:  
