version: '25.0.3'  
services:
  web:
    build: . 
    ports:
      - "3010:3010"  
    depends_on:
      - db  
    command: npm start

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:13
    env_file:
      - .env.example
    ports:
      - "5432:5432"  
    volumes:
      - db-data:/var/lib/postgresql/data 

volumes:
  db-data:  
