name: JavaScript Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Verify ESLint installation
      run: npx eslint --version

    - name: Run ESLint
      run: npx eslint .
