name: JavaScript Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install ESLint globally
      run: npm install -g eslint

    - name: Verify ESLint installation
      run: eslint --version

    - name: Install project dependencies
      run: npm ci

    - name: Run ESLint
      run: eslint .
