name: Lint Code Base

on: [push] 

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Upgrade Node.js to stable
      run: |
        npm install -g n
        sudo n stable

    - name: Install dependencies
      run: npm install

    - name: Upgrade ESLint to latest
      run: npm install eslint@latest

    - name: Run ESLint
      run: npx eslint .
