name: Lint Code Base

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.6.0'

    - name: Install dependencies
      run: npm install

    - name: Install specific ESLint version
      run: npm install eslint@8.45.0

    - name: Run ESLint with default settings
      run: npx eslint . --no-eslintrc --env node --env es2021
